# Generated by Django 3.0.2 on 2020-08-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='typ',
            field=models.CharField(choices=[('S', 'Serie'), ('M', 'Movie')], default='S', max_length=2),
            preserve_default=False,
        ),
    ]
