# Generated by Django 3.0.2 on 2020-08-26 01:47

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_film_typ'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('fb', models.CharField(default='', max_length=200)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'])),
            ],
        ),
        migrations.AlterField(
            model_name='film',
            name='typ',
            field=models.CharField(choices=[('S', 'Phim bộ'), ('M', 'Phim lẻ')], max_length=2),
        ),
        migrations.AddField(
            model_name='episode',
            name='translator',
            field=models.ManyToManyField(to='core.Translator'),
        ),
        migrations.AddField(
            model_name='movie',
            name='translator',
            field=models.ManyToManyField(to='core.Translator'),
        ),
    ]
