# Generated by Django 3.0.2 on 2020-08-31 12:47

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200826_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title']),
        ),
    ]
